# Generated by Django 4.0.4 on 2022-05-28 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userregistration',
            options={},
        ),
        migrations.AlterModelManagers(
            name='userregistration',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='userregistration',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='userregistration',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='userregistration',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='userregistration',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='userregistration',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='userregistration',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='userregistration',
            name='username',
        ),
    ]
