# Generated by Django 4.0.4 on 2022-05-29 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mAnalyzer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_keyword', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='TeamMemberName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('department', models.CharField(max_length=25)),
            ],
        ),
    ]
